### ISSUE TITLE
Error of making the bot

### ISSUE THREAD

**Issue by GENZxM** [StrawHat-Network/Shouko-KomiRobot#1]
Hi 😊 why i cannot deploy the app... Or maybe the Repo is not working???Can you help me

**Comment by Parth-Senpai** [comment]
wait

**Comment by Parth-Senpai** [comment]
We Have Fixed This Problem. 
This Occured as heroku banned our repo 
Maybe someone reported our repo 🤔 
You can deploy now 😊
